Add sentry integration
cyface-de/android-app pull request #5
Opened 2020-11-02 13:49 UTC by hb0

2020-11-09 14:03 UTC, muthenberg requested changes
One small comment

2020-11-10 07:42 UTC, hb0 commented on measuring-client/build.gradle
> +    file("local.properties").withInputStream { properties.load(it) }
This groovy method should auto-close the stream, see it's [documentation](http://docs.groovy-lang.org/latest/html/groovy-jdk/java/io/File.html):
"Create a new InputStream for this file and passes it into the closure. This method ensures the stream is closed after the closure returns."

2020-11-10 07:42 UTC, hb0 commented on measuring-client/build.gradle
> +    properties.load(new FileInputStream("local.properties"))
See below

2020-11-10 07:45 UTC, hb0 commented on measuring-client/build.gradle
> +    file("local.properties").withInputStream { properties.load(it) }
Didn't find or see anything else used in Gradle.

2020-11-10 14:13 UTC, muthenberg approved these changes

2020-11-11 06:05 UTC, merged